version: '3.8'

services:
  ticket-sales-postgres:
    image: postgres:17
    container_name: ticket-sales-postgres
    hostname: ticket-sales-postgres
    environment:
      POSTGRES_USER: ticket_sales
      POSTGRES_PASSWORD: Abc123456*
    ports:
      - "9001:5432"
    volumes:
      - ticket-sales-postgres-data:/var/lib/postgresql/data
    networks:
      - dev_network
  ticket-sales-mongo:
    image: mongo
    container_name: ticket-sales-mongo
    hostname: ticket-sales-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ticket_sales
      MONGO_INITDB_ROOT_PASSWORD: Abc123456*
    ports:
      - "9002:27017"
    volumes:
      - ticket-sales-mongo-data:/data/db
    networks:
      - dev_network

networks:
  dev_network:
    external: true

volumes:
  ticket-sales-postgres-data:
  ticket-sales-mongo-data:
